### ISSUE TITLE
Install drupal on windows

### ISSUE THREAD

**Issue by sayan801** [sayan801/DrupalModules#1]

**Comment by Satanik-technicise** [comment]
we will install drupal 7 from https://www.drupal.org/

**Comment by Satanik-technicise** [comment]
![drupal_installed](https://cloud.githubusercontent.com/assets/20014467/16175339/8a7d83e0-3607-11e6-806f-8eb3a588c346.jpg)

Drupal has been installed om windows. I have uploaded the picture. Take a look at it and tell me if anything is wrong

**Comment by Satanik-technicise** [comment]
Should I install ubuntu 16.04 LTS ?? Supported up to 2021-04.

**Comment by sayan801** [comment]
drupal installation looks ok.. This is a very basic version.. Try to install few more drupal modules.. Play around with look and feel...

**Comment by Satanik-technicise** [comment]
ok

**Comment by sayan801** [comment]
Please mention the steps you have used for installing drupal on windows..

**Comment by Satanik-technicise** [comment]
Step 1:- Download and install WAMP
Step 2:- Download Drupal from drupal.org
Step 3:- Extract the rar/zip folder inside localhost directory i.e wamp/www
Step 4:- Open localhost and drupal from browser http://localhost/drupal/
Step 5:- Then follow the installation steps as provided

**Comment by Satanik-technicise** [comment]
![1](https://cloud.githubusercontent.com/assets/20014467/16175771/17a2ca8c-3617-11e6-8ea5-c4f9c590e523.jpg)

After adding module and new theme

**Comment by Satanik-technicise** [comment]
![2](https://cloud.githubusercontent.com/assets/20014467/16175852/fde0b7c8-3619-11e6-9167-b782dae6a5cd.jpg)

After adding administration menu toolbar style module

**Comment by sayan801** [comment]
good Job..
